# GridWorld Policy Evaluation Assignment

## Objective
Given a 4x4 GridWorld where an agent starts at (0,0) and tries to reach (3,3), calculate the value function $V(s)$ for a random policy using Iterative Policy Evaluation.

- **Grid Size**: 4x4
- **Actions**: Up, Down, Left, Right (prob = 0.25 each)
- **Rewards**: -1 per step, 0 at terminal state (3,3)
- **Gamma**: 1.0 (No discounting)
- **Threshold**: 1e-4


In [5]:
import numpy as np

# Configuration
N = 4
gamma = 1.0
theta = 1e-4

## Helper Functions
Define the environment logic.

In [6]:
def is_terminal(state):
    return state == (N-1, N-1)

def step(state, action):
    # Actions: 0=Up, 1=Down, 2=Left, 3=Right
    r, c = state
    if action == 0: r -= 1
    if action == 1: r += 1
    if action == 2: c -= 1
    if action == 3: c += 1
    
    # Boundary Check: Stay in same place if hitting wall
    if r < 0 or r >= N or c < 0 or c >= N:
        r, c = state
        
    return (r, c)

## The Bellman Equation

We use the **Bellman Expectation Equation** for a specific policy $\pi$ to iteratively update the value of each state $s$. The equation is given by:

$$V_{k+1}(s) = \sum_{a} \pi(a|s) \sum_{s'} P(s'|s,a) [R(s,a,s') + \gamma V_k(s')]$$

Where:
- $\pi(a|s)$ is the probability of taking action $a$ in state $s$ (0.25 for all actions).
- $P(s'|s,a)$ is the transition probability (1.0 for deterministic moves).
- $R(s,a,s')$ is the reward (-1 for all transitions).
- $\gamma$ is the discount factor (1.0).
- $V_k(s')$ is the value of the next state from the previous iteration.

This update rule averages the expected returns from all possible future states.

## Iterative Policy Evaluation
Run the loop until convergence.

In [7]:
V = np.zeros((N, N))
actions = [0, 1, 2, 3]
prob = 0.25

iteration = 0
while True:
    delta = 0
    V_new = np.copy(V)
    
    for r in range(N):
        for c in range(N):
            state = (r, c)
            if is_terminal(state):
                continue
                
            v = V[r, c]
            new_val = 0
            
            # Bellman Equation Update
            for a in actions:
                next_state = step(state, a)
                reward = -1
                next_r, next_c = next_state
                
                new_val += prob * (reward + gamma * V[next_r, next_c])
            
            V_new[r, c] = new_val
            delta = max(delta, abs(v - new_val))
            
    V = V_new
    iteration += 1
    
    if delta < theta:
        print(f"Converged in {iteration} iterations")
        break

print("Final Value Function:")
print(V)

Converged in 471 iterations
Final Value Function:
[[-59.42367735 -57.42387125 -54.2813141  -51.71012579]
 [-57.42387125 -54.56699476 -49.71029394 -45.13926711]
 [-54.2813141  -49.71029394 -40.85391609 -29.99766609]
 [-51.71012579 -45.13926711 -29.99766609   0.        ]]
